# doc: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-github-packages
name: Publish package to GitHub Packages
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@${{ github.repository_owner }}'
      - run: echo "`jq -r '.name="@${{ github.repository }}"' package.json`" > package.json # npm.pkg.github.com 要求 package.json 中的 name 字段必须存在作用域且格式为: @scope/package-name
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm publish --registry=https://npm.pkg.github.com # 不添加 registry 会发布到: https://registry.npmjs.org, 参考: https://stackoverflow.com/a/66037808
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}